# Generated by Django 3.0.4 on 2020-03-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_comment_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='disabled',
            field=models.BooleanField(default=True, verbose_name='Wyłączone'),
        ),
        migrations.AddField(
            model_name='message',
            name='disabled',
            field=models.BooleanField(default=True, verbose_name='Wyłączone'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='disabled',
            field=models.BooleanField(default=True, verbose_name='Wyłączone'),
        ),
    ]
